# Generated by Django 6.0 on 2025-12-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='prodi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
